CREATE TABLE IF NOT EXISTS students (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sightings (
  id SERIAL PRIMARY KEY,
  student_id INT NOT NULL REFERENCES students(id) ON DELETE CASCADE ON UPDATE CASCADE,
  zone VARCHAR(100) NOT NULL,
  hora VARCHAR(60) NOT NULL,
  cantidad VARCHAR(30) NOT NULL,
  tamano VARCHAR(60) DEFAULT '',
  comportamiento VARCHAR(60) DEFAULT '',
  observaciones TEXT,
  fecha DATE DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sightings_student_id ON sightings(student_id);
