CREATE TABLE IF NOT EXISTS students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sightings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  zone VARCHAR(100) NOT NULL,
  hora VARCHAR(60) NOT NULL,
  cantidad VARCHAR(30) NOT NULL,
  tamano VARCHAR(60) DEFAULT '',
  comportamiento VARCHAR(60) DEFAULT '',
  observaciones TEXT,
  fecha DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_student_id (student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
